package com.example.mysubmissionapp;

import java.util.ArrayList;

public class CourseData {

    public static String[][] data = new String[][]{
            {"Membuat Aplikasi Android Pemula","Belajar Android untuk Pemula dengan Google Authorized Training Partner selama 30 hari!","https://www.dicoding.com/images/original/academy/belajar_membuat_aplikasi_android_untuk_pemula_logo_070119140911.jpg", "Peserta disarankan setidaknya memiliki pengetahuan tentang programming Java dan atau pemrograman berorientasi objek. Sistem pembelajaran adalah online (dapat diakses kapanpun dan darimanapun selama tersedia internet) dan kehadiran tatap muka tidak diperlukan.\n\nTools yang diwajibkan untuk kelas belajar Android ini adalah Android Studio. Peserta harus submit satu proyek akhir yang akan direview oleh developer expert untuk mendapatkan sertifikat dari kelas ini. Bila menginginkan materi yang lebih komprehensif, silahkan mengikuti kelas Menjadi Android Developer Expert.","https://www.dicoding.com/academies/51"},
            {"Web Fundamental","Ingin bisa membuat website? Daftar langsung kelas ini! Gratis!!!","https://www.dicoding.com/images/original/academy/web_fundamental_logo_030519090933.jpg","Website di era ini sudah menjadi kebutuhan utama yang tidak bisa dilupakan. Beberapa sektor seperti pemerintahan, bisnis, atau edukasi menggunakan website sebagai alat untuk promosi, management, tukar informasi, dan lainnya. Bahkan saat ini tidak jarang satu orang memiliki websitenya sendiri.Website adalah halaman informasi yang bisa diakses oleh siapapun dari seluruh penjuru dunia dengan menggunakan koneksi internet. Per Januari 2019 terdapat 1.518.207.413 website yang aktif, berdasarkan survey dari Webcraft Webserver Survey.\n\nDi kelas ini Anda akan belajar tentang komponen-komponen dasar untuk membuat suatu website, antara lain HTML, CSS dan JavaScript.Kelas ini sangat cocok bagi Anda yang masih pemula dan ingin mempelajari bagaimana menjadi developer web.\n\nJika Anda ingin belajar di kelas ini, silakan baca blog untuk setting environmentnya terlebih dahulu, link ke blog.Kelas ini berdasarkan pembelajaran yang ada di website Codepolitan. Kelas ini menggabungkan 2 kelas menjadi 1, yaitu kelas html css, dan kelas JavaScript.","https://www.dicoding.com/academies/123"},
            {"Java Fundamental","Kelas Introductory Java", "https://www.dicoding.com/images/original/academy/java_fundamental_logo_080119141920.jpg","Java adalah sebuah bahasa yang diciptakan oleh James Gosling di tahun 1990-an. Saat itu, paradigma Write Once, Run Anywhere (WORA) belum populer. Bahasa-bahasa yang ada perlu ditulis sangat spesifik berdasarkan platformnya. Maka muncullah Java sebagai bahasa yang dapat dijalankan di berbagai platform tanpa perlu melakukan re-kompilasi. Java membawa pendekatan konkurensi, berbasis kelas, dan tentunya berorientasi objek. Program yang dibuat di atas bahasa Java akan dijalankan pada Java Runtime Environment (JRE), sebuah lingkungan virtual yang dibuat sehingga mampu mengakomodasi paradigma WORA.\n\nBahasa Java termasuk bahasa yang sangat populer digunakan untuk mengembangkan aplikasi hingga 2019. Menurut statistik, Bahasa Java digunakan 90% perusahaan terkemuka yang masuk dalam daftar Fortune 500. Bahasa Java dapat digunakan untuk mengembangkan Aplikasi pada platform desktop, web, mobile, hingga embedded dan IoT.","https://www.dicoding.com/academies/60"},
            {"Belajar Membuat Game Pemula", "Belajar Mengembangkan Game dengan Kurikulum dari Asosiasi Game Indonesia selama 30 Hari!","https://www.dicoding.com/images/original/academy/belajar_membuat_game_untuk_pemula_logo_070119140848.jpg","Semua modul dalam kelas ini telah diverifikasi langsung oleh Asosiasi Game Indonesia (AGI) untuk memastikan materi yang diajarkan relevan dan sesuai dengan kebutuhan industri game saat ini. Terdapat 26 modul yang merupakan bagian dari kelas Menjadi Game Developer Expert.\n\nPeserta akan belajar basic scripting untuk membuat game. Peserta juga akan belajar membuat game Arcade.\n\nScripting akan menggunakan bahasa C# dan peserta yang telah memiliki pengetahuan baik bahasa C# maupun Pemrograman Berorientasi Objek bahasa apapun. Setiap modul dilengkapi dengan project file untuk referensi, namun orisinalitas project tugas menjadi prasyarat utama dalam penilaian.","https://www.dicoding.com/academies/58"},
            {"Memulai Pemrograman Dengan Kotlin","Kelas pengantar untuk mempelajari Functional Programming serta OOP menggunakan Kotlin","https://www.dicoding.com/images/original/academy/kotlin_fundamental_logo_010219112628.jpg","Pada tahun 2010 lalu JetBrains memulai sebuah proyek open-sources baru. Proyek ini merupakan sebuah bahasa pemrograman statically typed yang menargetkan JVM, Android, JavaScript dan Native. Kotlin -nama sebuah pulau di Rusia- menjadi inspirasi oleh tim pengembang untuk ditetapkan sebagai nama bahasa pemrograman tersebut. Kotlin pertama kali dirilis pada bulan Februari 2016 dengan versi 1.0. Saat ini sudah mencapai versi 1.3.30 per rilis 12 April 2019 lalu.\n\nKotlin dapat digunakan untuk berbagai macam pengembangan aplikasi, baik itu server atau backend, website, maupun mobile Android. Bahkan saat ini tengah dikembangkan Kotlin/Native. Apa uniknya? Kotlin/Native memungkinkan developer untuk menggunakannya sebagai bahasa pemrograman dalam pengembangan aplikasi di platform lain seperti embedded system, desktop, macOS, dan iOS. Bahkan tak menutup kemungkinan Kotlin juga bisa digunakan untuk data science. Menarik, bukan?\n\nKotlin merupakan bahasa pemrograman berorientasi objek dan fungsional. Kotlin sangat terkenal di kalangan developer dengan semua kemudahan dan fitur yang ditawarkannya. Oleh karena itu, akademi ini didirikan agar pengguna Kotlin dapat memiliki pemahaman mendalam tentang konsep dasar Kotlin.\n\nMateri di dalamnya akan membimbing peserta mulai dari konsep dasar, pemrograman fungsional, pemrograman berorientasi objek, hingga akhirnya tiba di Concurrency pada Kotlin.","https://www.dicoding.com/academies/80"},
            {"Membangun Progressive Web Apps","Mari belajar Progressive Web App, website kekinian dengan fungsionalitas seperti desktop, mobile App","https://www.dicoding.com/images/original/academy/membangun_progressive_web_apps_logo_070119142922.jpg","Progressive Web Apps menyajikan pengalaman pengguna layaknya aplikasi native. PWA merupakan aplikasi web dengan beragam fitur web modern, seperti: Mengubah sajian tampilan yang umumnya dibuka melalui halaman browser menjadi jendela aplikasi tersendiri, Menyajikan aplikasi web yang dapat diandalkan, cepat, dan menjaga ikatan dengan pengguna, Memungkinkan konten halaman diakses dalam mode offline, menampilkan pesan pemberitahuan, hingga akses ke hardware dari perangkat seperti halnya native app dan Banyak perusahaan telah mengadopsi PWA.\n\nDeveloper dengan skill PWA lebih dilirik oleh perusahaan. ","https://www.dicoding.com/academies/74"},
            {"Menjadi Flutter Developer Expert","Jadilah developer yang dapat membuat aplikasi cross-platform (Android, iOS) yang cantik dan juga mudah.","https://www.dicoding.com/images/original/academy/flutter_academy_logo_140319093702.jpg","Flutter adalah teknologi untuk membangun suatu mobile apps yang dibuat oleh Google. Dengan menggunakan Flutter, Anda dapat membuat aplikasi Android dan iOS sekaligus. Flutter menggunakan bahasa Dart yang juga dibuat oleh Google dan merupakan bahasa general purpose. Artinya, Dart mampu berjalan di banyak platform.\n\nFlutter merupakan cross-platform framework,  alias aplikasi yang dapat digunakan di lebih dari satu platform. Aplikasi yang dibuat dengan menggunakan Flutter dapat dijalankan baik di platform Android maupun iOS. Tentu hal ini akan menghemat waktu. Anda pun tidak perlu mempelajari bahasa native yang digunakan di masing-masing platform.","https://www.dicoding.com/academies/110"},
            {"Menjadi Android Developer Expert","Jadilah expert di dunia pemrograman Android. Materi disusun oleh Dicoding sebagai Google Authorized Training Partner","https://www.dicoding.com/images/original/academy/menjadi_android_developer_expert_logo_070119140352.jpg","Android semakin digandrungi. Per Maret 2018 ada lebih dari 3,6 juta aplikasi Android di Google Play Store (Statista). Di indonesia sendiri pada bulan Maret 2019 sebanyak 93,5% konsumen memilih platform Android untuk sistem operasi peranti mobile mereka (Statcounter). Ini menandakan bahwa kebutuhan akan Android developer, semakin meningkat. Tak heran, profesi Android developer merupakan 1 dari 5 profesi yang paling diincar perusahaan (LinkedIn Emerging Jobs Report 2019).\n\nDicoding sebagai satu-satunya Google Developers Authorized Training Partner di Indonesia telah melalui proses penyusunan kurikulum secara komprehensif. Semua modul telah diverifikasi langsung oleh Google untuk memastikan bahwa materi yang diajarkan relevan dan sesuai dengan kebutuhan industri digital saat ini.","https://www.dicoding.com/academies/14"},
            {"Kotlin Android Developer Expert","Kuasai Kotlin, bahasa pemrograman yang didukung penuh Google untuk mengembangkan aplikasi Android","https://www.dicoding.com/images/original/academy/kotlin_android_developer_expert_logo_070119140227.jpg","Pada Google I/O 2017, Kotlin diumumkan sebagai bahasa pemrograman yang termasuk dalam bahasa kelas satu (First class) yang didukung untuk pembuatan aplikasi Android, selain Java dan C++. Kotlin adalah bahasa pemrograman yang dibuat oleh JetBrains.\n\nGoogle juga akan memastikan bahwa semua fitur baru di Android, framework, IDE dan keseluruhan library, akan dapat bekerja dan terintegrasi baik dengan bahasa pemrograman Kotlin serta interopable dengan fungsi-fungsi Java yang telah ada sehingga memungkinkan para engineer melakukan perubahan bagian tertentu aplikasi dari Java ke Kotlin dan sebaliknya dengan sangat mudah.Kotlin memungkinkan untuk kita menuliskan kode-kode dalam pengembangan aplikasi Android menjadi lebih sederhana dan mudah dipahami. Beberapa perusahaan besar pun sudah menerapkan Kotlin sebagai bahasa pemrograman untuk pengembangan aplikasi Android.\n\nSelain itu, animo para Android developer di Indonesia pun sangat besar untuk mempelajari Kotlin secara mendalam. Bahkan, hampir setiap perusahaan yang membutuhkan Android developer telah menetapkan kemampuan dalam menguasai Kotlin sebagai nilai tambah dalam kualifikasi perekrutannya.","https://www.dicoding.com/academies/55"},
            {"Menjadi Game Developer Expert", "Jadilah seorang Game dev pro. Dapatkan pengalaman bikin 8 jenis Game di kelas ini, sekarang!", "https://www.dicoding.com/images/original/academy/menjadi_game_developer_expert_logo_070119140532.jpg","Jadilah seorang Game Dev pro. Dapatkan pengalaman bikin 8 jenis Game di kelas ini, sekarang!\n\nProfesi game dev di Indonesia, sangat menjanjikan. Potensi industri Game nasional sangat pesat. Tahun 2017 nilainya tercatat Rp 11 triliun dan tumbuh 25-30 % per tahun (Kompas). Di kelas ini Anda akan berlatih jadi seorang Game dev pro yang BISA membuat Game sesuai kebutuhan industri terkini.","https://www.dicoding.com/academies/47"}
    };

    public static ArrayList<Course> getListData(){
        Course course = null;

        ArrayList<Course> list = new ArrayList<>();

        for (String[] aData : data){
            course = new Course();
            course.setName(aData[0]);
            course.setDetail(aData[1]);
            course.setPhoto(aData[2]);
            course.setDescription(aData[3]);
            course.setAddress(aData[4]);
            list.add(course);
        }
        return list;
    }
}
